name: Nix Build
on:
  push:
    branches:
      - main
  pull_request:
      branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    name: Nix Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        hosts: [desktop, nas, work, macbook]
        # include/exclude don't support arrays
        # https://github.com/orgs/community/discussions/7835
        include:
          - os: ubuntu-latest
            hosts: desktop
          - os: ubuntu-latest
            hosts: nas
          - os: ubuntu-latest
            hosts: work
          - os: macos-latest
            hosts: macbook
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Nix Build
        run: nix build .#${{ matrix.hosts }}
